import streamlit as st
import pandas as pd
import torch
import numpy as np
import plotly.graph_objects as go
import plotly.express as px
import networkx as nx
from fpdf import FPDF
from models.hybrid_model import HybridModel

st.set_page_config(page_title="GCN-GRU Social Profile Inspector", layout="wide", page_icon="🕵️")

# Custom CSS for aesthetics and animations
st.markdown("""
<style>
/* Gradient Text for Headers */
h1, h2, h3 {
    background: -webkit-linear-gradient(45deg, #FF4B4B, #FF8F00, #F433AB);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    animation: gradient 3s ease infinite;
}

/* Metric card styling */
div[data-testid="stMetricValue"] {
    font-size: 2rem;
    font-weight: bold;
    text-shadow: 2px 2px 4px rgba(0,0,0,0.5);
}

/* Add hover scale animation to the main block elements */
div[data-testid="stBlock"] {
    transition: transform 0.2s ease-in-out;
}
div[data-testid="stBlock"]:hover {
    transform: scale(1.01);
}
</style>
""", unsafe_allow_html=True)

st.title("🕵️ GCN-GRU Social Profile Inspector")
st.markdown("This dashboard leverages a **Hybrid Graph Neural Network & GRU** model to detect coordinates behavior and determine whether a profile is Authentic or Inauthentic.")

@st.cache_resource
def load_model_and_data():
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    
    # Load dataset
    try:
        df = pd.read_csv("dataset.csv")
    except FileNotFoundError:
        st.error("dataset.csv not found! Please run train.py first.")
        return None, None, None, None
        
    # Load processed graph data
    try:
        data, temporal_x = torch.load("processed_data.pt", weights_only=False)
        data = data.to(device)
        temporal_x = temporal_x.to(device)
    except FileNotFoundError:
        st.error("processed_data.pt not found! Please run train.py first.")
        return None, None, None, None
        
    # Load model
    gcn_in_channels = data.x.size(1)
    model = HybridModel(gcn_in_channels=gcn_in_channels, gru_input_size=1, num_classes=3).to(device)
    try:
        model.load_state_dict(torch.load("hybrid_model.pth", weights_only=True))
        model.eval()
    except Exception as e:
        st.error(f"Failed to load model weights: {e}")
        return None, None, None, None

    # Compute all predictions once for efficiency
    with torch.no_grad():
        logits = model(data.x, data.edge_index, temporal_x)
        probs = torch.softmax(logits, dim=1)
        preds = logits.argmax(dim=1).cpu().numpy()
        probs = probs.cpu().numpy()
        
    return df, preds, probs, data

df, preds, probs, data = load_model_and_data()

# PDF Generator Function
def create_pdf(user_id, status, risk_score, metrics):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("helvetica", "B", 16)
    pdf.cell(200, 10, txt="GCN-GRU Social Profile Inspector - Risk Report", ln=True, align='C')
    pdf.ln(10)
    pdf.set_font("helvetica", "", 12)
    pdf.cell(200, 10, txt=f"Profile Evaluated: User #{user_id}", ln=True)
    pdf.cell(200, 10, txt=f"Model Conclusion: {status}", ln=True)
    pdf.cell(200, 10, txt=f"Calculated Risk Score: {risk_score:.1f}/100", ln=True)
    pdf.ln(5)
    pdf.set_font("helvetica", "B", 14)
    pdf.cell(200, 10, txt="Behavioral Metrics Snapshot:", ln=True)
    pdf.set_font("helvetica", "", 12)
    for k, v in metrics.items():
        pdf.cell(200, 10, txt=f"  - {k}: {v}", ln=True)
    
    pdf.ln(10)
    pdf.set_font("helvetica", "I", 10)
    pdf.cell(200, 10, txt="Report automatically generated by GCN-GRU Threat Intelligence Engine.", ln=True)
    return pdf.output(dest='S').encode('latin-1')

if df is not None:
    class_names = ['Authentic', 'Potentially Inauthentic', 'Inauthentic']
    
    # ✅ Fix mismatch between dataset and predictions
    min_len = min(len(df), len(preds))

    if len(df) != len(preds):
        st.warning(f"Dataset size ({len(df)}) and prediction size ({len(preds)}) mismatch. Aligning automatically.")

    df = df.iloc[:min_len].copy()
    preds = preds[:min_len]
    probs = probs[:min_len]

    # ✅ Safe assignment
    df['Predicted_Class'] = [class_names[p] for p in preds]
    df['Authentic_Prob'] = probs[:, 0]
    df['Potentially_Inauthentic_Prob'] = probs[:, 1]
    df['Inauthentic_Prob'] = probs[:, 2]    
    
    # --- SIDEBAR ---
    st.sidebar.image("https://cdn-icons-png.flaticon.com/512/2102/2102633.png", width=100)
    st.sidebar.header("Filter & Search")
    
    filter_option = st.sidebar.selectbox(
        "Show Profiles:",
        ("All Profiles", "Potentially Inauthentic Only", "Inauthentic Only", "Flagged (Both)")
    )
    
    # Filter dataset based on selection
    if filter_option == "Potentially Inauthentic Only":
        filtered_df = df[df['Predicted_Class'] == 'Potentially Inauthentic']
    elif filter_option == "Inauthentic Only":
        filtered_df = df[df['Predicted_Class'] == 'Inauthentic']
    elif filter_option == "Flagged (Both)":
        filtered_df = df[df['Predicted_Class'].isin(['Potentially Inauthentic', 'Inauthentic'])]
    else:
        filtered_df = df
        
    st.sidebar.write(f"**Found {len(filtered_df)} profiles.**")
    
    # User selection
    if len(filtered_df) > 0:
        user_list = filtered_df.index.tolist()
        user_id = st.sidebar.selectbox("Select User ID to Inspect:", user_list)
    else:
        st.sidebar.warning("No profiles match this filter.")
        st.stop()
        
    # Stats overview for the sidebar
    st.sidebar.markdown("---")
    st.sidebar.subheader("Global Network Stats")
    auth_pct = (preds == 0).sum() / len(preds) * 100
    pot_pct = (preds == 1).sum() / len(preds) * 100
    inauth_pct = (preds == 2).sum() / len(preds) * 100
    st.sidebar.write(f"🟢 Authentic: {auth_pct:.2f}%")
    st.sidebar.write(f"🟠 Potentially: {pot_pct:.2f}%")
    st.sidebar.write(f"🔴 Inauthentic: {inauth_pct:.2f}%")
    
    # --- MAIN DASHBOARD SUMMARY ---
    st.header(f"Inspecting User Profile: #{user_id}")
    predicted_class_id = preds[user_id]
    predicted_class_name = class_names[predicted_class_id]
    
    # Add animations based on finding
    if predicted_class_id == 0:
        st.success(f"**Final Verdict:** {predicted_class_name} ✅")
        # st.balloons() can be triggered here if desired, but might be annoying on every reload
    elif predicted_class_id == 1:
        st.warning(f"**Final Verdict:** {predicted_class_name} ⚠️")
    else:
        st.error(f"**Final Verdict:** {predicted_class_name} 🚨")
    
    # Risk Score Logic (0 to 100)
    user_risk_score = (probs[user_id][1] * 50) + (probs[user_id][2] * 100)
    
    col_meter, col_bars = st.columns(2)
    
    with col_meter:
        # Risk Meter Plotly
        fig_gauge = go.Figure(go.Indicator(
            mode = "gauge+number",
            value = user_risk_score,
            domain = {'x': [0, 1], 'y': [0, 1]},
            title = {'text': "Account Risk Meter (0-100)"},
            gauge = {
                'axis': {'range': [None, 100], 'tickwidth': 1, 'tickcolor': "white"},
                'bar': {'color': "white", 'thickness': 0.25},
                'bgcolor': "black",
                'borderwidth': 2,
                'bordercolor': "gray",
                'steps': [
                    {'range': [0, 33], 'color': "#2e7d32"},     # Green
                    {'range': [33, 66], 'color': "#ff8f00"},    # Orange
                    {'range': [66, 100], 'color': "#d32f2f"}],  # Red
                'threshold': {
                    'line': {'color': "white", 'width': 4}, 
                    'thickness': 0.75, 
                    'value': user_risk_score}
            }))
        fig_gauge.update_layout(height=300, margin=dict(l=10, r=10, t=40, b=10))
        st.plotly_chart(fig_gauge, use_container_width=True)

    with col_bars:
        # Confidence Bars Plotly
        confidence_data = pd.DataFrame({
            'Class': ['Inauthentic', 'Potentially Inauthentic', 'Authentic'],
            'Confidence': [probs[user_id][2], probs[user_id][1], probs[user_id][0]]
        })
        fig_bar = px.bar(confidence_data, x='Confidence', y='Class', orientation='h', 
                         title='Model Confidence Distribution',
                         color='Class', color_discrete_map={
                             'Authentic': '#2e7d32', 
                             'Potentially Inauthentic': '#ff8f00', 
                             'Inauthentic': '#d32f2f'
                         }, text_auto='.1%')
        fig_bar.update_layout(xaxis_tickformat='.0%', showlegend=False, height=300)
        st.plotly_chart(fig_bar, use_container_width=True)

    st.markdown("---")
    
    # --- CHARTS AND METRICS VS AVERAGE ---
    st.subheader("Profile Behavioral Analysis")
    user_data = df.iloc[user_id]
    avgs = df[['app_usage_time_min', 'message_sent_count', 'swipe_right_ratio', 'likes_received', 'mutual_matches', 'emoji_usage_rate']].mean()
    
    c1, c2 = st.columns([1, 2])
    
    # Capture metrics for PDF report
    report_metrics = {
        "App Usage (min)": f"{user_data.get('app_usage_time_min', 0):.0f} (Avg: {avgs['app_usage_time_min']:.0f})",
        "Messages Sent": f"{user_data.get('message_sent_count', 0):.0f} (Avg: {avgs['message_sent_count']:.0f})",
        "Swipe Right Ratio": f"{user_data.get('swipe_right_ratio', 0):.2f} (Avg: {avgs['swipe_right_ratio']:.2f})",
        "Likes Received": f"{user_data.get('likes_received', 0):.0f} (Avg: {avgs['likes_received']:.0f})",
        "Mutual Matches": f"{user_data.get('mutual_matches', 0):.0f} (Avg: {avgs['mutual_matches']:.0f})",
        "Emoji Usage Rate": f"{user_data.get('emoji_usage_rate', 0):.2f} (Avg: {avgs['emoji_usage_rate']:.2f})"
    }
    
    with c1:
        st.markdown("### User vs Network Averages")
        for k, v in report_metrics.items():
            st.write(f"**{k}:** {v}")
            
        # PDF EXPORT BUTTON
        st.markdown("<br>", unsafe_allow_html=True)
        pdf_bytes = create_pdf(user_id, predicted_class_name, user_risk_score, report_metrics)
        st.download_button(
            label="📄 Download Official PDF Report", 
            data=pdf_bytes, 
            file_name=f"User_{user_id}_Risk_Report.pdf", 
            mime="application/pdf",
            use_container_width=True,
            type="primary"
        )

    with c2:
        categories = ['Usage Time', 'Messages', 'Swipe Ratio', 'Likes', 'Matches', 'Emojis']
        def norm(val, col):
            return min(val / df[col].max(), 1.0) if df[col].max() > 0 else 0
            
        user_radar_vals = [
            norm(user_data['app_usage_time_min'], 'app_usage_time_min'),
            norm(user_data['message_sent_count'], 'message_sent_count'),
            norm(user_data['swipe_right_ratio'], 'swipe_right_ratio'),
            norm(user_data['likes_received'], 'likes_received'),
            norm(user_data['mutual_matches'], 'mutual_matches'),
            norm(user_data['emoji_usage_rate'], 'emoji_usage_rate')
        ]
        
        avg_radar_vals = [
            norm(avgs['app_usage_time_min'], 'app_usage_time_min'),
            norm(avgs['message_sent_count'], 'message_sent_count'),
            norm(avgs['swipe_right_ratio'], 'swipe_right_ratio'),
            norm(avgs['likes_received'], 'likes_received'),
            norm(avgs['mutual_matches'], 'mutual_matches'),
            norm(avgs['emoji_usage_rate'], 'emoji_usage_rate')
        ]
        
        fig_radar = go.Figure()
        fig_radar.add_trace(go.Scatterpolar(r=user_radar_vals + [user_radar_vals[0]], theta=categories + [categories[0]], fill='toself', name=f'User #{user_id}'))
        fig_radar.add_trace(go.Scatterpolar(r=avg_radar_vals + [avg_radar_vals[0]], theta=categories + [categories[0]], fill='toself', name='Network Average'))
        fig_radar.update_layout(polar=dict(radialaxis=dict(visible=True, range=[0, 1])), showlegend=True, margin=dict(l=20, r=20, t=20, b=20), height=300)
        st.plotly_chart(fig_radar, use_container_width=True)

    st.markdown("---")
    
    # --- 3D NETWORK VISUALIZATION ---
    st.subheader("3D Network Connection Graph")
    st.write("Visualizing the user's local neighborhood generated by the Cosine Similarity Graph.")
    
    edges_from_user = data.edge_index[1][data.edge_index[0] == user_id].cpu().numpy()
    edges_to_user = data.edge_index[0][data.edge_index[1] == user_id].cpu().numpy()
    connected_nodes = list(set(edges_from_user).union(set(edges_to_user)))
    
    if len(connected_nodes) == 0:
        st.info("This user has no direct connections greater than the similarity threshold.")
    else:
        st.write(f"Found **{len(connected_nodes)}** connected 1st-degree neighbors.")
        
        subgraph_nodes = [user_id] + connected_nodes
        if len(subgraph_nodes) > 100:
            subgraph_nodes = subgraph_nodes[:100]
            
        subgraph_nodes_set = set(subgraph_nodes)
        
        all_src = data.edge_index[0].cpu().numpy()
        all_dst = data.edge_index[1].cpu().numpy()
        
        mask = np.isin(all_src, subgraph_nodes) & np.isin(all_dst, subgraph_nodes)
        sub_src = all_src[mask]
        sub_dst = all_dst[mask]
        
        G = nx.Graph()
        for node in subgraph_nodes:
            G.add_node(node, pred=preds[node])
            
        for s, d in zip(sub_src, sub_dst):
            G.add_edge(s, d)
            
        pos = nx.spring_layout(G, dim=3, seed=42)
        
        edge_x, edge_y, edge_z = [], [], []
        for edge in G.edges():
            x0, y0, z0 = pos[edge[0]]
            x1, y1, z1 = pos[edge[1]]
            edge_x.extend([x0, x1, None])
            edge_y.extend([y0, y1, None])
            edge_z.extend([z0, z1, None])
            
        edge_trace = go.Scatter3d(
            x=edge_x, y=edge_y, z=edge_z,
            line=dict(width=1, color='#888'),
            hoverinfo='none',
            mode='lines'
        )
        
        node_x, node_y, node_z, node_colors, node_texts, node_sizes = [], [], [], [], [], []
        
        for node in G.nodes():
            x, y, z = pos[node]
            node_x.append(x)
            node_y.append(y)
            node_z.append(z)
            
            p_class = preds[node]
            if node == user_id:
                node_colors.append("blue")
                node_sizes.append(15)
                node_texts.append(f"<b>TARGET USER #{node}</b><br>{class_names[p_class]}")
            else:
                if p_class == 0:
                    node_colors.append("#2e7d32") # Green
                elif p_class == 1:
                    node_colors.append("#ff8f00") # Orange
                else:
                    node_colors.append("#d32f2f") # Red
                node_sizes.append(8)
                node_texts.append(f"User #{node}<br>{class_names[p_class]}")
                
        node_trace = go.Scatter3d(
            x=node_x, y=node_y, z=node_z,
            mode='markers',
            hoverinfo='text',
            text=node_texts,
            marker=dict(
                showscale=False,
                color=node_colors,
                size=node_sizes,
                line=dict(width=2, color='#2F4F4F')
            )
        )
        
        fig_3d = go.Figure(data=[edge_trace, node_trace],
             layout=go.Layout(
                showlegend=False,
                hovermode='closest',
                margin=dict(b=0, l=0, r=0, t=0),
                scene=dict(
                    xaxis=dict(showgrid=False, zeroline=False, showticklabels=False),
                    yaxis=dict(showgrid=False, zeroline=False, showticklabels=False),
                    zaxis=dict(showgrid=False, zeroline=False, showticklabels=False),
                )
             ))
             
        st.plotly_chart(fig_3d, use_container_width=True)
        st.caption("🟢 Authentic | 🟠 Potentially Inauthentic | 🔴 Inauthentic | 🔵 Current Selected User")